# Generated by Django 4.1.3 on 2022-11-06 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('isbn_no', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MaxLengthValidator(13, message='As per ISBN standard, all ISBNs are 13-digits long.'), django.core.validators.MinLengthValidator(13, message='As per ISBN standard, all ISBNs are 13-digits long.')], verbose_name='ISBN')),
                ('author_name', models.CharField(max_length=150)),
                ('genre', models.CharField(max_length=100)),
                ('inventory', models.IntegerField(default=0)),
            ],
        ),
    ]
